[2015-12-24 17:51:30,931][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: Run test]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 82, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 66, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 35, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-24 17:51:30,932][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpmkwGnU]
[2015-12-24 17:51:30,932][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-24 17:51:30,948][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: Get ip]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 82, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 66, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 35, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-24 17:51:30,948][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpdXlgdH]
[2015-12-24 17:51:30,948][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:32:52,194][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: Run test]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 84, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 68, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 36, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:32:52,195][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpim1vuR]
[2015-12-25 18:32:52,195][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:32:52,211][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: Get ip]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 84, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 68, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 36, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:32:52,211][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpco3nSn]
[2015-12-25 18:32:52,211][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:34:49,172][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: Code]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 84, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 68, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 36, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:34:49,173][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmp_w5x7Z]
[2015-12-25 18:34:49,173][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:34:49,188][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: 596926]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 84, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 68, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 36, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:34:49,188][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpHxT105]
[2015-12-25 18:34:49,189][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:34:49,205][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>存在不支持的自定义格式的参数命令,[command: get]</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 84, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 68, in runCommand</br>    comm_dict = cls.getMail()</br></br>  File "run.py", line 36, in getMail</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"存在不支持的自定义格式的参数命令,[command: %s]"% part)</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:34:49,205][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmp1T98lg]
[2015-12-25 18:34:49,205][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:43:32,878][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:43:32,879][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpkgGb2i]
[2015-12-25 18:43:32,879][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:45:16,112][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:45:16,113][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpZAvCTr]
[2015-12-25 18:45:16,113][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:49:27,556][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:49:27,556][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmp077tMc]
[2015-12-25 18:49:27,557][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-25 18:49:47,483][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-25 18:49:47,484][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpVl3C5h]
[2015-12-25 18:49:47,484][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-28 16:23:32,694][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-28 16:23:32,694][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmp1BAp1i]
[2015-12-28 16:23:32,694][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-28 16:37:02,885][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-28 16:37:02,886][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpp2pETi]
[2015-12-28 16:37:02,886][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
[2015-12-28 16:43:36,002][140735334535936][INFO][mail.py][line:122] [func:__excute] [msg:Subject: =?UTF-8?B?W2Rldl1bemJxXVttYWlsX3F1ZXJ5XVt6aGFuZ2Jhb3FpbmdzLWlNYWMubG9jYWxd6Ieq5a6a5LmJ55qE6YKu5Lu25ZG95Luk?=
MIME-Version: 1.0
From: myownwork@app.xiaomi.com
To: zhangbaoqing@xiaomi.com
Content-Type: text/html;charset=utf-8

原始收件人是：zhangbaoqing(Cc:None)</br>------------------------------</br>口令不匹配</br></br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br><strong>异常信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>None</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br><strong>堆栈信息:</strong></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br>  File "run.py", line 83, in <module></br>    RunScript.runCommand()</br></br>  File "run.py", line 71, in runCommand</br>    Email.send_to_maintainers(u"自定义的邮件命令", u"口令不匹配")</br></br>  File "/Users/zhangbaoqing/work/receive_mail/util/mail.py", line 47, in send_to_maintainers</br>    content += "\n".join(traceback.format_stack())</br></br>------------------------------------------------------------------------------------------------------------------------------------------------------</br></br></br></br></br>如有疑问，请及时联系运维权限平台管理员(zhangbaoqing)]
[2015-12-28 16:43:36,002][140735334535936][INFO][mail.py][line:123] [func:__excute] [msg:/usr/sbin/sendmail -f  'myownwork@app.xiaomi.com' 'zhangbaoqing@xiaomi.com' < /var/folders/tj/4wdj73hs6fvg_kwq3t_qhgm80000gn/T/tmpqk_9kN]
[2015-12-28 16:43:36,002][140735334535936][INFO][mail.py][line:124] [func:__excute] [msg:mail command exec result: ]
